let data, rows = [], chartDays = [];
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = (v, digits=0) => Number(v).toLocaleString('en-US',{maximumFractionDigits:digits});
const money = v => v == null ? 'No plan' : '$' + num(v,2);
const sum = (items,key) => items.reduce((a,b)=>a + Number(b[key] || 0),0);
const siteName = id => data.sites.find(s=>s.site_id===id)?.site_name || id;
const roleName = id => data.roles.find(r=>r.role_id===id)?.planning_role || id;
const pretty = s => s.replaceAll('_',' ');
function badge(status){return `<span class="badge ${status==='INFEASIBLE'||status==='UNKNOWN'?'bad':status==='FEASIBLE'?'warn':''}">${esc(status)}</span>`;}
function render(){
 setupPacking();
 const run = data.planning_runs.find(r=>r.productivity_case===$('case').value);
 const packing = data.packing?.scenarios.find(s=>s.scenario===$('demand')?.value);
 $('case').disabled=!!packing;
 const capacityRows=packing?packing.baseline_daily.map(r=>({...r,run_id:run.run_id})):data.daily_capacity_results;
 const valid = $('start').value && $('end').value && $('start').value<=$('end').value;
 $('range-error').hidden=!!valid;
 rows=capacityRows.filter(r=>valid&&r.run_id===run.run_id&&($('site').value==='all'||r.site_id===$('site').value)&&r.planning_date>=$('start').value&&r.planning_date<=$('end').value);
 $('export').disabled=!rows.length;
 const staffing=data.staffing_plans.filter(s=>s.run_id===run.run_id&&($('site').value==='all'||s.site_id===$('site').value));
 const metrics=[['Required productive hours',num(sum(rows,'required_hours'),1),'Full workload before service target'],['Capacity gap',num(sum(rows,'capacity_gap_hours'),1)+' h','Sum of daily role-level shortfalls'],['Daily active positions',num(sum(staffing,'scheduled_headcount')),'All four roles; modeled staffing'],['Direct scheduled wages',money(sum(rows,'scheduled_wage_cost')),'Picking and packing only']];
 $('metrics').innerHTML=metrics.map(m=>`<div class="metric"><small>${m[0]}</small><strong>${m[1]}</strong><p>${m[2]}</p></div>`).join('');
 $('period').textContent=`${$('start').value} to ${$('end').value}`;
 $('sites').innerHTML=data.sites.filter(s=>$('site').value==='all'||s.site_id===$('site').value).map(s=>{const r=rows.filter(x=>x.site_id===s.site_id);return `<tr><td><button class="site-link" data-site="${esc(s.site_id)}">${esc(s.site_name)}</button><p style="font-size:10px;margin:6px 0 0">${esc(s.benchmark_geography)}</p></td><td>${num(sum(staffing.filter(x=>x.site_id===s.site_id),'scheduled_headcount'))}</td><td>${num(sum(r,'required_hours'),1)}</td><td>${num(sum(r,'capacity_gap_hours'),1)}</td><td>${r.length?num(100*sum(r,'service_target_met')/r.length,1)+'%':'N/A'}</td><td>${money(sum(r,'scheduled_wage_cost'))}</td></tr>`;}).join('');
 $('daily').innerHTML=rows.slice().sort((a,b)=>a.planning_date.localeCompare(b.planning_date)).map(r=>`<tr><td>${r.planning_date}</td><td>${esc(siteName(r.site_id))}</td><td>${esc(roleName(r.role_id))}</td><td>${num(r.required_hours,1)}</td><td>${num(r.available_productive_hours,1)}</td><td>${num(r.capacity_gap_hours,1)}</td></tr>`).join('');
 const days=new Map(); rows.forEach(r=>{if(!days.has(r.planning_date))days.set(r.planning_date,{date:r.planning_date,required:0,available:0});const d=days.get(r.planning_date);d.required+=r.required_hours;d.available+=r.available_productive_hours;});chartDays=[...days.values()].sort((a,b)=>a.date.localeCompare(b.date));drawChart();
 $('chart-detail').textContent=rows.length?'Daily totals; individual role shortages can occur even when network capacity is sufficient.':'No records in the selected date range.';
}
function drawChart(){
 const canvas=$('chart'),w=canvas.clientWidth,h=canvas.clientHeight;if(!w)return;const scale=window.devicePixelRatio||1;canvas.width=w*scale;canvas.height=h*scale;const ctx=canvas.getContext('2d');ctx.scale(scale,scale);const left=48,right=w-12,top=12,bottom=h-30;const max=Math.max(1,...chartDays.flatMap(d=>[d.required,d.available]))*1.15;
 ctx.font='10px Arial';ctx.fillStyle='#7c8980';ctx.strokeStyle='#e2e8e4';for(let i=0;i<=4;i++){const y=bottom-(bottom-top)*i/4;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillText(num(max*i/4),0,y+3);}
 const x=i=>left+(right-left)*i/Math.max(1,chartDays.length-1),y=v=>bottom-v/max*(bottom-top);
 for(const [key,color] of [['required','#25816b'],['available','#6b89b6']]){ctx.beginPath();chartDays.forEach((d,i)=>i?ctx.lineTo(x(i),y(d[key])):ctx.moveTo(x(i),y(d[key])));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash(key==='available'?[6,4]:[]);ctx.stroke();if(key==='required'&&chartDays.length){ctx.lineTo(x(chartDays.length-1),bottom);ctx.lineTo(left,bottom);ctx.closePath();ctx.fillStyle='#25816b12';ctx.fill();}}
 ctx.setLineDash([]);ctx.fillStyle='#7c8980';const step=Math.max(1,Math.ceil(chartDays.length/(w<450?3:7)));chartDays.forEach((d,i)=>{if(i%step===0)ctx.fillText(d.date.slice(5),x(i)-12,h-8);});
}
function selectScenario(index){const s=data.optimizer.scenarios[index],solved=['OPTIMAL','FEASIBLE'].includes(s.status);$('scenario-detail').innerHTML=`<div class="section-heading"><h2>${esc(pretty(s.scenario))}</h2>${badge(s.status)}</div><p class="scope">${solved?`${s.actions.length} saved actions. Service target: ${num(s.policy.service_target*100)}%. Synthetic workers and policies.`:'No feasible action plan is available for this scenario.'}</p>${solved?`<div class="table-wrap"><table><thead><tr><th>Action</th><th>Date</th><th>Site</th><th>Paid hours</th><th>Incremental cost</th></tr></thead><tbody>${s.actions.map(a=>`<tr><td>${esc(pretty(a.kind))}</td><td>${esc(a.date||a.start_date||'See action record')}</td><td>${esc(siteName(a.site_id||a.destination_site||''))}</td><td>${a.paid_hours==null?'N/A':num(a.paid_hours,2)}</td><td>${money(a.incremental_cost)}</td></tr>`).join('')}</tbody></table></div>`:''}`;}
function showView(view){for(const id of ['portfolio','network','builder','recommendations','methodology','overview','scenarios','tableau','evidence'])$(id).hidden=id!==view;document.body.classList.toggle('legacy-active',view==='overview');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('title').textContent={portfolio:'Demand overview',network:'Network capacity',builder:'Scenario comparison',recommendations:'Recommendations',methodology:'Methodology',overview:'Legacy network model',scenarios:'Legacy scenario comparison',tableau:'Published dashboards',evidence:'Data register'}[view];$('subtitle').textContent={portfolio:'Observed warehouse demand and workload concentration.',network:'Replay observed 2023 workload across three modeled sites and fixed staffing assumptions.',builder:'Compare two precomputed staffing policies under shared assumptions.',recommendations:'Actions supported by the current evidence and validation.',methodology:'How the evidence, assumptions, service target, and decision rules fit together.',overview:'Historical network model retained for methodology review.',scenarios:'Saved workforce actions from the legacy network model.',tableau:'Interactive portfolio analysis published on Tableau Public.',evidence:'Source provenance and the assumptions behind each result.'}[view];$('context-notice').hidden=!['overview','scenarios'].includes(view);$('export').hidden=view!=='overview';if(view==='overview')drawChart();if(view==='portfolio'&&window.drawPortfolioDemand)window.drawPortfolioDemand();if(view==='network'&&window.drawNetworkCapacity)window.drawNetworkCapacity();}
function enableStaticMode(){
 $('loading').hidden=true;
 document.querySelectorAll('[data-local-only]').forEach(element=>element.hidden=true);
 document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>showView(button.dataset.view));
}
async function init(){try{const response=await fetch('/api/data');if(!response.ok)throw Error('Planning data could not be loaded. Check the server and database, then reload.');data=await response.json();$('loading').hidden=true;$('overview').hidden=false;$('site').insertAdjacentHTML('beforeend',data.sites.map(s=>`<option value="${esc(s.site_id)}">${esc(s.site_name)}</option>`).join(''));const dates=data.modeled_daily_workload.map(r=>r.planning_date).sort();for(const id of ['start','end']){$(id).min=dates[0];$(id).max=dates.at(-1);}function reset(){$('site').value='all';$('case').value='base';$('start').value=dates[0];$('end').value=dates.at(-1);render();}$('reset').onclick=reset;['site','case','start','end'].forEach(id=>$(id).onchange=render);$('sites').onclick=e=>{const b=e.target.closest('[data-site]');if(b){$('site').value=b.dataset.site;render();}};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
 $('stale').hidden=data.optimizer_current;$('scenario-list').innerHTML=data.optimizer.scenarios.map((s,i)=>`<tr><td>${esc(pretty(s.scenario))}</td><td>${esc(s.productivity_case)}</td><td>${badge(s.status)}</td><td>${money(s.incremental_cost)}</td><td>${s.best_bound_cost==null?'N/A':money(s.best_bound_cost)}</td><td><button data-scenario="${i}">View plan</button></td></tr>`).join('');$('scenario-list').onclick=e=>{const b=e.target.closest('[data-scenario]');if(b)selectScenario(Number(b.dataset.scenario));};selectScenario(0);
 $('sources').innerHTML=data.source_registry.map(s=>`<article><h3>${esc(s.source_name)} <span class="badge">${esc(s.evidence_class)}</span></h3><p>${esc(s.publisher)} &middot; ${esc(s.release_period)}<br>${esc(s.limitations)}</p>${/^https?:\/\//.test(s.source_url||'')?`<a href="${esc(s.source_url)}" target="_blank" rel="noopener noreferrer">Source record</a>`:''}</article>`).join('');$('assumptions').innerHTML=data.scenario_assumptions.map(a=>`<tr><td>${esc(pretty(a.assumption_key))}</td><td>${esc(a.numeric_value??a.text_value)} ${esc(a.unit)}</td><td>${esc(pretty(a.classification))}</td><td>${esc(a.basis)}</td></tr>`).join('');$('quality').innerHTML=[...data.data_quality_results,...data.planning_quality_results].map(q=>`<span class="badge ${q.status==='PASS'?'':'bad'}">${esc(pretty(q.check_name))}: ${esc(q.status)}</span>`).join('');reset();
 }catch(error){enableStaticMode();$('export').disabled=true;}}
 function setupPacking(){
  if($('demand')||!data.packing)return;
  const label=document.createElement('label');label.textContent='Workload model';const select=document.createElement('select');select.id='demand';select.innerHTML='<option value="legacy">Legacy baseline</option>'+data.packing.scenarios.map(s=>`<option value="${esc(s.scenario)}">Packing: ${s.assumed_units_per_job} units/job (assumed)</option>`).join('');label.append(select);document.querySelector('.filters').prepend(label);
  const note=document.createElement('p');note.id='packing-note';note.className='notice';note.textContent='Legacy baseline selected. Revised packing sensitivities are available; all productivity rates remain uncalibrated.';document.querySelector('.filters').after(note);
  select.onchange=()=>{$('case').value='base';note.textContent=select.value==='legacy'?'Legacy baseline selected. Revised packing sensitivities are available; all productivity rates remain uncalibrated.':`Assumed packing hours with base picking demand. Site allocation uses benchmark employment shares. ${data.packing_current?'Saved inputs match.':'Saved inputs have changed; regenerate results.'}`;render();};
  const reset=$('reset').onclick;$('reset').onclick=()=>{select.value='legacy';select.onchange();reset();};
  const offset=data.optimizer.scenarios.length;data.optimizer.scenarios.push(...data.packing.scenarios);
  $('scenario-list').insertAdjacentHTML('beforeend',data.packing.scenarios.map((s,i)=>`<tr><td>${esc(pretty(s.scenario))}<p>Assumed, uncalibrated</p></td><td>${esc(s.productivity_case)}</td><td>${badge(s.status)}</td><td>${money(s.incremental_cost)}</td><td>${s.best_bound_cost==null?'N/A':money(s.best_bound_cost)}</td><td><button data-scenario="${i+offset}">View plan</button></td></tr>`).join(''));
  if(!data.packing_current){$('stale').hidden=false;$('stale').textContent='Saved packing inputs have changed. Regenerate the packing optimization results.';}
  document.querySelector('#evidence .scope').textContent='Revised packing sensitivities use productive hours in the network optimizer. Packing time and job sizes are uncalibrated assumptions; picking remains at the historical baseline. Recruiting pipelines, dated absences, and backlog are not represented.';
 }
 $('export').onclick=()=>{const keys=['planning_date','site_id','role_id','required_hours','available_productive_hours','capacity_gap_hours','scheduled_wage_cost'];const csv=[['workload_model','evidence_class',...keys].join(','),...rows.map(r=>[$('demand')?.value||'legacy','assumed_uncalibrated',...keys.map(k=>r[k])].join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`capacity-${$('demand')?.value||'legacy'}-${$('case').value}-${$('site').value}-${$('start').value}.csv`;a.click();URL.revokeObjectURL(url);};
 $('chart').onmousemove=e=>{if(!chartDays.length)return;const i=Math.max(0,Math.min(chartDays.length-1,Math.round((e.offsetX-48)/Math.max(1,$('chart').clientWidth-60)*(chartDays.length-1))));const d=chartDays[i];$('chart-detail').textContent=`${d.date} | Required: ${num(d.required,1)} h | Available: ${num(d.available,1)} h`;};
 window.addEventListener('resize',drawChart);init();
