const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[];
    page.on('pageerror', e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:8765');
    await page.locator('#portfolio-metrics strong').first().waitFor();
    assert.equal(await page.locator('#portfolio-metrics strong').first().textContent(),'228,195');
    assert.equal(await page.locator('#mix-bars strong').last().textContent(),'79.9%');
    await page.click('[data-view="builder"]');
    assert.equal(await page.locator('#scenario-cards .scenario-score strong').first().textContent(),'96.1%');
    assert.equal(await page.locator('#scenario-cards .scenario-score strong').last().textContent(),'100.0%');
    assert((await page.locator('#scenario-comparison-summary').textContent()).includes('+3.9 pts'));
    const comparisonDownload=page.waitForEvent('download');
    await page.click('#scenario-export');
    const comparison=await comparisonDownload;
    const comparisonCsv=fs.readFileSync(await comparison.path(),'utf8');
    assert.equal(comparisonCsv.trim().split('\n').length,3);
    assert(comparisonCsv.includes('extra0_ot2_temps0'));
    assert(comparisonCsv.includes('extra4_ot2_temps0'));
    const reportDownload=page.waitForEvent('download');
    await page.click('#decision-report');
    const report=await reportDownload;
    const reportText=fs.readFileSync(await report.path(),'utf8');
    assert(reportText.includes('DECISION REPORT'));
    assert(reportText.includes('does not prescribe actual headcount'));
    await page.click('[data-view="methodology"]');
    assert((await page.locator('#methodology').textContent()).includes('Observed demand'));
    assert((await page.locator('#methodology').textContent()).includes('not a prescribed headcount'));
    await page.click('[data-view="recommendations"]');
    assert((await page.locator('#recommendations').textContent()).includes('36/36 listed later-period stresses'));
    await page.click('[data-view="network"]');
    assert.equal(await page.locator('#network-metrics strong').nth(1).textContent(),'190.9 h');
    assert.equal(await page.locator('#network-sites tr').count(),3);
    assert((await page.locator('#network-period').textContent()).includes('178 recorded dates'));
    await page.selectOption('#network-site','joliet');
    assert.equal(await page.locator('#network-sites tr').count(),1);
    assert.equal(await page.locator('#network-metrics strong').nth(2).textContent(),'10');
    await page.selectOption('#network-site','all');
    await page.selectOption('#network-case','low');
    assert.equal(await page.locator('#network-metrics strong').nth(1).textContent(),'567.9 h');
    await page.selectOption('#network-case','high');
    assert.equal(await page.locator('#network-metrics strong').nth(1).textContent(),'72.3 h');
    await page.screenshot({path:'/tmp/workforce-network-2023-desktop.png',fullPage:true});
    await page.click('[data-view="overview"]');
    assert((await page.locator('#context-notice').textContent()).includes('Historical 2011 demand'));
    assert.equal(await page.locator('#sites tr').count(),3);
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'/tmp/workforce-dashboard-mobile.png',fullPage:true});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert.deepEqual(errors,[]);
    assert.equal((await page.request.get('http://127.0.0.1:8765/.env')).status(),404);
    console.log('PASS: 2023 demand, network capacity sensitivities, scenario comparison/export, methodology, recommendations, mobile layout, and route isolation.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
